### ISSUE TITLE
Pipeline runner: "##[error]Could not queue the build because there were validation errors or warnings."

### ISSUE THREAD

**Issue by alexvaccaro** [microsoft/CSEDevOps#12]
I am getting a generic error when running one of my pipelines:
"##[error]Could not queue the build because there were validation errors or warnings."

Running the build with diagnostics on is not giving any further details, is there a way to see what these "errors or warnings" are?

**Comment by tsluyter** [comment]
@alexvaccaro please close this issue, as this issue does not appear to be related to the ZAP plugin.
