### ISSUE TITLE
Reporting outputs are empty since latest OWASPZAP Docker image update

### ISSUE THREAD

**Issue by mcalnd70** [microsoft/CSEDevOps#23]
Since the recent OWASP ZAP Docker image was changed on 7th October 2021 - this AZDO task has broken irreparably. I found that the report output coming out of this task was empty, therefore breaking the reporting out

I've since had no option but to stop using this task and fix our pipelines

For anyone else struggling, my pipeline looks like this - you will see I no longer use this task. I hope this helps someone else struggling - Cheers

```
# AZDO YAML Pipeline for OWASP ZAP Docker to a run baseline scan against a website URL
# Neil McA - Oct 2021

# A few sources used for this...
# OWASP ZAP Docker Image: https://www.zaproxy.org/docs/docker/about/
# zap-baseline.py reference: https://www.zaproxy.org/docs/docker/baseline-scan/
# Post N-Unit format reporting: https://github.com/microsoft/CSEDevOps/blob/main/Zap/README.md#install-handlebars

name: $(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranch)

trigger:
- main
- master

stages:
- stage: OWASP_ZAP_Stage # !CHANGE! per env
  jobs:
    - job : OWASP_ZAP
      variables: 
        websiteurl: 'www.kylie.com'     
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Bash@3
        displayName: 'Prepare OWASPZAP output directory for Docker'
        inputs:
          targetType: 'inline'
          script: |
            sudo mkdir $(System.DefaultWorkingDirectory)/owaspzap
            sudo chmod -R 777 $(System.DefaultWorkingDirectory)/owaspzap
      - task: Bash@3
        displayName: 'Run OWASPZAP Docker Image and scan $(websiteurl)'
        inputs:
          targetType: 'inline'
          script: |
            docker run -t -v $(System.DefaultWorkingDirectory)/owaspzap:/zap/wrk:rw owasp/zap2docker-stable zap-baseline.py -t http://$(websiteurl) -J report.json -I
      - bash: |
          sudo npm install -g handlebars-cmd

          cat <<EOF > owaspzap/nunit-template.hbs

          <test-run
              id="2"
              name="Owasp test"
              start-time="{{@generated}}">
              {{#each site}}<test-suite
                  id="{{@index}}"
                  type="Assembly"
                  name="{{[@name]}}"
                  result="Failed"
                  failed="{{alerts.length}}">
                  <attachments>
                      <attachment>
                          <filePath>$BUILD_SOURCESDIRECTORY/owaspzap/report.html</filePath>
                      </attachment>
                  </attachments>
                  {{#each alerts}}<test-case
                      id="{{@index}}"
                      name="{{alert}}"
                      result="Failed"
                      fullname="{{alert}}"
                      time="1">
                      <failure>
                          <message>
                              <![CDATA[{{{desc}}}]]>
                          </message>
                          <stack-trace>
                              <![CDATA[
          Solution:
          {{{solution}}}

          Reference:
          {{{reference}}}

          instances:{{#each instances}}
          * {{uri}}
              - {{method}}
              {{#if evidence}}- {{{evidence}}}{{/if}}
                              {{/each}}]]>
                          </stack-trace>
                      </failure>
                  </test-case>
                  {{/each}}
              </test-suite>
              {{/each}}
          </test-run>
          EOF
        displayName: 'OWASP NUnit template'
      - bash: ' handlebars owaspzap/report.json < owaspzap/nunit-template.hbs > owaspzap/$(websiteurl).xml'
        displayName: 'Generate NUnit type file for $(websiteurl)'
      # Publish results to AZDO Test page                                                             
      - task: PublishTestResults@2
        displayName: 'Publish Test Results to AZDO'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: 'owaspzap/$(websiteurl).xml'
          testRunTitle: '$(websiteurl)'

```

**Comment by mgrandillo** [comment]
Hi guys!

I have adapted the script above to run in our ADO pipeline. The issue I am seeing is that the tests report errors but they should be shown as warnings or informational since the results in the logs show up as INFO. When running the zap instance standalone, the tests are reported as warnings and not failures. Also, I do not see any passed test results. See below the contents of logs and test results. I have also attached the script(yaml).

![image](https://user-images.githubusercontent.com/57016398/155154516-56f10c74-6f80-4fac-9038-34f3319544be.png)

![image](https://user-images.githubusercontent.com/57016398/155154837-6181beed-d2ac-4e7e-857d-e58294e45980.png)

#name: Set dynamically below in a task

name: $(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranch) 

trigger:
- master

stages:
- stage: OWASP_ZAP_Stage # !CHANGE! per env
  jobs:
    - job : OWASP_ZAP
      variables: 
        websiteurl: 'https://dbservice.gendev.net/status'     
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Bash@3
        displayName: 'Prepare OWASPZAP output directory for Docker'
        inputs:
          targetType: 'inline'
          script: |
            sudo mkdir $(System.DefaultWorkingDirectory)/owaspzap
            sudo chmod -R 777 $(System.DefaultWorkingDirectory)/owaspzap
      - task: Bash@3
        displayName: 'Run OWASPZAP Docker Image and scan $(websiteurl)'
        inputs:
          targetType: 'inline'
          script: |
            docker run -t -v $(System.DefaultWorkingDirectory)/owaspzap:/zap/wrk:rw owasp/zap2docker-stable zap-baseline.py -t $(websiteurl) -J report.json -i --autooff
      
      - bash: |
          sudo npm install -g handlebars-cmd

          cat <<EOF > owaspzap/nunit-template.hbs

          <test-run
              id="2"
              name="Owasp test"
              start-time="{{@generated}}">
              {{#each site}}<test-suite
                  id="{{@index}}"
                  type="Assembly"
                  name="{{[@name]}}"
                  result="Failed"
                  failed="{{alerts.length}}">
                  <attachments>
                      <attachment>
                          <filePath>$BUILD_SOURCESDIRECTORY/owaspzap/report.html</filePath>
                      </attachment>
                  </attachments>
                  {{#each alerts}}<test-case
                      id="{{@index}}"
                      name="{{alert}}"
                      result="Failed"
                      fullname="{{alert}}"
                      time="1">
                      <failure>
                          <message>
                              <![CDATA[{{{desc}}}]]>
                          </message>
                          <stack-trace>
                              <![CDATA[
          Solution:
          {{{solution}}}

          Reference:
          {{{reference}}}

          instances:{{#each instances}}
          * {{uri}}
              - {{method}}
              {{#if evidence}}- {{{evidence}}}{{/if}}
                              {{/each}}]]>
                          </stack-trace>
                      </failure>
                  </test-case>
                  {{/each}}
              </test-suite>
              {{/each}}
          </test-run>
          EOF
        displayName: 'OWASP NUnit template'
      - bash: ' handlebars owaspzap/report.json < owaspzap/nunit-template.hbs > owaspzap/test-results.xml'
        displayName: 'Generate NUnit type file for $(websiteurl)'
      # Publish results to AZDO Test page                                                             
      - task: PublishTestResults@2
        displayName: 'Publish Test Results to AZDO'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: 'owaspzap/test-results.xml'
          testRunTitle: '$(websiteurl)'
          failTaskOnFailedTests: false        
        condition: always()

**Comment by mcalnd70** [comment]
I'll close this issue as it is probably not going to be actioned and there are workarounds - as above
