### ISSUE TITLE
Context file documentation

### ISSUE THREAD

**Issue by HFSWO** [microsoft/CSEDevOps#9]
Is there any documentation of the context file format (structure, keys, ...)? I would like to use it for authentication and to do some more specific testing, but haven't found any information about it.

**Comment by CrazyKidJack** [comment]
I am also looking for this. I checked the ZAP documentation but didn't find much. 
I did find [this ](https://nullsweep.com/dynamic-security-scanning-in-a-ci-zap-scanning-with-jenkins/) one article that gives an example of the formatting... but doesn't really explain how to make your own from scratch

**Comment by tsluyter** [comment]
All documentation for context files needs to be read on the official ZAP website. -> https://www.zaproxy.org/docs/desktop/start/

ZAP is not a Microsoft product and also not part of this particular project on Github. This project only relates to the Azure DevOps plugin to use zap2docker; nothing else.

**Comment by tsluyter** [comment]
@HFSWO   I have created a pull request for this project, including links to the relevant documentation. 

-> https://github.com/microsoft/CSEDevOps/pull/16

Please verify and then close this issue.
